### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by xorinzor** [alex-oleshkevich/vue-tabler-icons#4]
When importing this module via: `import VueTablerIcons  from 'vue-tabler-icons';` 
it will throw an error when compiling for every individual icon:

```ERROR in ./node_modules/vue-tabler-icons/icons/AntennaBars2Icon.js
Module not found: Error: Can't resolve 'babel-helper-vue-jsx-merge-props' in '<snip>\node_modules\vue-tabler-icons\icons'
 @ ./node_modules/vue-tabler-icons/icons/AntennaBars2Icon.js 1:0-62 17:20-34
 @ ./node_modules/vue-tabler-icons/icons.js
 @ ./node_modules/vue-tabler-icons/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

**Comment by alex-oleshkevich** [comment]
Fixed in 1.8.1.
Thanks for the tip!

**Comment by xorinzor** [comment]
Thanks for the quick fix!

**Comment by amirasyraf** [comment]
@alex-oleshkevich Seems like this issue is still present in 1.10?

e.g.
```
Module not found: Error: Can't resolve '@vue/babel-helper-vue-jsx-merge-props' in '../node_modules/vue-tabler-icons/icons'
```

**Comment by xorinzor** [comment]
@alex-oleshkevich can confirm what @amirasyraf says. It doesn't seem to be installed as a dependency automatically.
